name: google
version: 0.0.1
authors: Collin Jackson jackson@google.com
description: A Dart wrapper for Google SDKs.
homepage: https://github.com/flutter/google-dart/
environment:
  sdk: '>=1.9.0 <2.0.0'
